export const CHANGE_DESK = "CHANGE_DESK"
export const UPLOAD = "UPLOAD"
export const SET_COLUMNS_NAMES = "SET_COLUMNS_NAMES"
export const SET_DATA_VALUES = "SET_DATA_VALUES"
export const UPDATE_DATASET_INFO = "UPDATE_DATASET_INFO"
export const SET_NUMBER_OF_DATAROWS_TO_BE_SHOWN = "SET_NUMBER_OF_DATAROWS_TO_BE_SHOWN"

export const CHOOSE_LAYER_TYPE = "CHOOSE_LAYER_TYPE"

export const SET_MODEL_LAYERS = "SET_MODEL_LAYERS"


export const REMOVE_LAYER_FROM_MODEL = "REMOVE_LAYER_FROM_MODEL"

export const SET_CURRENT_DENSE_LAYER = "SET_CURRENT_DENSE_LAYER"


